//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvinsAIRARefactored.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarvinsAIRARefactored.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminBoxx.
        /// </summary>
        internal static string AdminBoxx {
            get {
                return ResourceManager.GetString("AdminBoxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marvin&apos;s Awesome iRacing App.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Force.
        /// </summary>
        internal static string AutoForce {
            get {
                return ResourceManager.GetString("AutoForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Margin.
        /// </summary>
        internal static string AutoMargin {
            get {
                return ResourceManager.GetString("AutoMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias.
        /// </summary>
        internal static string Bias {
            get {
                return ResourceManager.GetString("Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Rate.
        /// </summary>
        internal static string CompressionRate {
            get {
                return ResourceManager.GetString("CompressionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %/Nm.
        /// </summary>
        internal static string CompressionRateUnits {
            get {
                return ResourceManager.GetString("CompressionRateUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To AdminBoxx.
        /// </summary>
        internal static string ConnectToAdminBoxx {
            get {
                return ResourceManager.GetString("ConnectToAdminBoxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Protection.
        /// </summary>
        internal static string CrashProtection {
            get {
                return ResourceManager.GetString("CrashProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curb Protection.
        /// </summary>
        internal static string CurbProtection {
            get {
                return ResourceManager.GetString("CurbProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Force.
        /// </summary>
        internal static string CurrentForce {
            get {
                return ResourceManager.GetString("CurrentForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Limit.
        /// </summary>
        internal static string DeltaLimit {
            get {
                return ResourceManager.GetString("DeltaLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Limiter.
        /// </summary>
        internal static string DeltaLimiter {
            get {
                return ResourceManager.GetString("DeltaLimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Limiter On 60 Hz.
        /// </summary>
        internal static string DeltaLimiterOn60Hz {
            get {
                return ResourceManager.GetString("DeltaLimiterOn60Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nm/s.
        /// </summary>
        internal static string DeltaLimitUnits {
            get {
                return ResourceManager.GetString("DeltaLimitUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Boost.
        /// </summary>
        internal static string DetailBoost {
            get {
                return ResourceManager.GetString("DetailBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Booster.
        /// </summary>
        internal static string DetailBooster {
            get {
                return ResourceManager.GetString("DetailBooster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Booster On 60 Hz.
        /// </summary>
        internal static string DetailBoosterOn60Hz {
            get {
                return ResourceManager.GetString("DetailBoosterOn60Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade force feedback when entering or exiting car.
        /// </summary>
        internal static string FadeForceFeedback {
            get {
                return ResourceManager.GetString("FadeForceFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Reduction.
        /// </summary>
        internal static string ForceReduction {
            get {
                return ResourceManager.GetString("ForceReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friction.
        /// </summary>
        internal static string Friction {
            get {
                return ResourceManager.GetString("Friction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Force.
        /// </summary>
        internal static string GForce {
            get {
                return ResourceManager.GetString("GForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  g.
        /// </summary>
        internal static string GForceUnits {
            get {
                return ResourceManager.GetString("GForceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        internal static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Data.
        /// </summary>
        internal static string HeaderData {
            get {
                return ResourceManager.GetString("HeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Force.
        /// </summary>
        internal static string MaxForce {
            get {
                return ResourceManager.GetString("MaxForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia Timer Jitter.
        /// </summary>
        internal static string MultimediaTimerJitter {
            get {
                return ResourceManager.GetString("MultimediaTimerJitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native 360 Hz.
        /// </summary>
        internal static string Native360Hz {
            get {
                return ResourceManager.GetString("Native360Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native 360 Hz Torque.
        /// </summary>
        internal static string Native360HzTorque {
            get {
                return ResourceManager.GetString("Native360HzTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native 60 Hz.
        /// </summary>
        internal static string Native60Hz {
            get {
                return ResourceManager.GetString("Native60Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native 60 Hz Torque.
        /// </summary>
        internal static string Native60HzTorque {
            get {
                return ResourceManager.GetString("Native60HzTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No Attached Force Feedback Devices Found].
        /// </summary>
        internal static string NoAttachedFFBDevicesFound {
            get {
                return ResourceManager.GetString("NoAttachedFFBDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Features.
        /// </summary>
        internal static string OtherFeatures {
            get {
                return ResourceManager.GetString("OtherFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output 500 Hz Torque.
        /// </summary>
        internal static string Output500HzTorque {
            get {
                return ResourceManager.GetString("Output500HzTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Strength.
        /// </summary>
        internal static string OverallStrength {
            get {
                return ResourceManager.GetString("OverallStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked Strength.
        /// </summary>
        internal static string ParkedStrength {
            get {
                return ResourceManager.GetString("ParkedStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Force.
        /// </summary>
        internal static string PeakForce {
            get {
                return ResourceManager.GetString("PeakForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Press The Record Button].
        /// </summary>
        internal static string PressTheRecordButton {
            get {
                return ResourceManager.GetString("PressTheRecordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing Wheel.
        /// </summary>
        internal static string RacingWheel {
            get {
                return ResourceManager.GetString("RacingWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing Wheel Device.
        /// </summary>
        internal static string RacingWheelDevice {
            get {
                return ResourceManager.GetString("RacingWheelDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sec.
        /// </summary>
        internal static string SecondsUnits {
            get {
                return ResourceManager.GetString("SecondsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Information.
        /// </summary>
        internal static string SessionInformation {
            get {
                return ResourceManager.GetString("SessionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock Velocity.
        /// </summary>
        internal static string ShockVelocity {
            get {
                return ResourceManager.GetString("ShockVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  m/s.
        /// </summary>
        internal static string ShockVelocityUnits {
            get {
                return ResourceManager.GetString("ShockVelocityUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        internal static string Simulator {
            get {
                return ResourceManager.GetString("Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The iRacing simulator is not running.
        /// </summary>
        internal static string SimulatorNotRunning {
            get {
                return ResourceManager.GetString("SimulatorNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Lock Strength.
        /// </summary>
        internal static string SoftLockStrength {
            get {
                return ResourceManager.GetString("SoftLockStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        internal static string Switches {
            get {
                return ResourceManager.GetString("Switches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry Data.
        /// </summary>
        internal static string TelemetryData {
            get {
                return ResourceManager.GetString("TelemetryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ThisLanguage {
            get {
                return ResourceManager.GetString("ThisLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topmost Window.
        /// </summary>
        internal static string TopmostWindow {
            get {
                return ResourceManager.GetString("TopmostWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nm.
        /// </summary>
        internal static string TorqueUnits {
            get {
                return ResourceManager.GetString("TorqueUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Button Mappings.
        /// </summary>
        internal static string UpdateButtonMappings {
            get {
                return ResourceManager.GetString("UpdateButtonMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Waiting For Input].
        /// </summary>
        internal static string WaitingForInput {
            get {
                return ResourceManager.GetString("WaitingForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ze Alan Le Twist.
        /// </summary>
        internal static string ZeAlanLeTwist {
            get {
                return ResourceManager.GetString("ZeAlanLeTwist", resourceCulture);
            }
        }
    }
}
