; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppFile "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\MarvinsAIRARefactored.exe"
#define MyAppName "AdminBoxx"
#define MyAppIconName "AdminBoxx"
; the app's version scheme is three-part (2.1.[buildStamp]) but the exe's numeric version resource is
; always padded to four parts with a trailing ".0" - trim it so the installer name matches the app version
#define MyAppVersionFull GetFileVersion(MyAppFile)
#define MyAppVersion Copy(MyAppVersionFull, 1, Len(MyAppVersionFull) - 2)
#define MyAppPublisher "Marvin Herbold"
#define MyAppURL "https://adminboxx.com"
#define MyAppExeName "AdminBoxx.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E8E1E83E-0006-4576-8751-8AC695D05F38}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=AdminBoxx-Setup-{#MyAppVersion}
OutputDir=userdocs:AdminBoxx
SetupIconFile=C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\Artwork\AppIcon\adminboxx.ico
SolidCompression=yes
WizardStyle=modern
CloseApplications=yes
RestartApplications=yes
; Code signing (Azure Artifact Signing). Active only when compiled with /DSignedBuild,
; which build-adminboxx.ps1 passes alongside the /Smssign=... sign-tool command. When set,
; Inno signs BOTH the generated installer and its embedded uninstaller. Compiling this
; script directly in the Inno IDE (without the define) skips signing so the build still
; succeeds.
#ifdef SignedBuild
SignTool=mssign
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{userdocs}\AdminBoxx"
Name: "{userdocs}\AdminBoxx\Sounds"

[Files]
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\MarvinsAIRARefactored.exe"; DestName: "AdminBoxx.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\createdump.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.config"; DestDir: "{app}"; Flags: ignoreversion

Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\Sounds\AdminBoxx\*.wav"; DestDir: "{userdocs}\AdminBoxx\Sounds\AdminBoxx"; Flags: ignoreversion recursesubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppIconName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppIconName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[InstallDelete]
Type: files; Name: "{userstartup}\AdminBoxx.lnk"

[UninstallDelete]
Type: files; Name: "{userstartup}\AdminBoxx.lnk"
