; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppFile "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\MarvinsAIRARefactored.exe"
#define MyAppName "Marvin's Awesome iRacing App"
#define MyAppIconName "MAIRA"
; the app's version scheme is three-part (2.1.[buildStamp]) but the exe's numeric version resource is
; always padded to four parts with a trailing ".0" - trim it so the installer name matches the app version
#define MyAppVersionFull GetVersionNumbersString(MyAppFile)
#define MyAppVersion Copy(MyAppVersionFull, 1, Len(MyAppVersionFull) - 2)
#define MyAppPublisher "Marvin Herbold"
#define MyAppURL "https://herboldracing.com"
#define MyAppExeName "MarvinsAIRARefactored.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{49221926-0B97-4313-B82A-7ADD3B922AED}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=MAIRA-Setup-{#MyAppVersion}
OutputDir=userdocs:MAIRA
SetupIconFile=C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\Artwork\AppIcon\maira-universal.ico
SolidCompression=yes
WizardStyle=modern
CloseApplications=yes
RestartApplications=yes
LicenseFile=Legal.txt
; Code signing (Azure Artifact Signing). Active only when compiled with /DSignedBuild,
; which build-release.ps1 passes alongside the /Smssign=... sign-tool command. When set,
; Inno signs BOTH the generated installer and its embedded uninstaller. Compiling this
; script directly in the Inno IDE (without the define) skips signing so the build still
; succeeds.
#ifdef SignedBuild
SignTool=mssign
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{userdocs}\MAIRA"
Name: "{userdocs}\MAIRA\Sounds"
Name: "{userdocs}\MAIRA\Recordings"
Name: "{userdocs}\MAIRA\Calibration"
Name: "{userdocs}\MAIRA\TTS"
Name: "{userdocs}\MAIRA\SimHub"

[Files]
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\MarvinsAIRARefactored\bin\publish\*.config"; DestDir: "{app}"; Flags: ignoreversion

Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\Calibration\*.csv"; DestDir: "{userdocs}\MAIRA\Calibration"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\SBT\*"; DestDir: "{userdocs}\MAIRA\SBT"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\SimHub\*"; DestDir: "{userdocs}\MAIRA\SimHub"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\Sounds\*.wav"; DestDir: "{userdocs}\MAIRA\Sounds"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\TTS\*"; DestDir: "{userdocs}\MAIRA\TTS"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\SimHub\MairaSimHubPlugin.dll"; DestDir: "{code:SimHubRoot}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\SimHub\MairaTyphoonWindSimHubPlugin.dll"; DestDir: "{code:SimHubRoot}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\marvi\OneDrive\Documents\GitHub\MarvinsAIRARefactored\InnoSetup\SimHub\MairaSbtSimHubPlugin.dll"; DestDir: "{code:SimHubRoot}"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppIconName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppIconName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[InstallDelete]
Type: files; Name: "{userstartup}\MAIRA.lnk"
; leftovers from the retired "Refactored" naming - old startup / start menu / desktop shortcuts and the
; old-named SimHub plugin (both the copy inside the SimHub install and the staged copy in the documents
; folder, which the PrepareToInstall migration may have just carried over into the MAIRA folder)
Type: files; Name: "{userstartup}\MarvinsAIRA Refactored.lnk"
Type: files; Name: "{autoprograms}\MarvinsAIRA Refactored.lnk"
Type: files; Name: "{autodesktop}\MarvinsAIRA Refactored.lnk"
Type: files; Name: "{code:SimHubRoot}\MarvinsAIRARefactoredSimHub.dll"
Type: files; Name: "{userdocs}\MAIRA\SimHub\MarvinsAIRARefactoredSimHub.dll"
Type: files; Name: "{userdocs}\MAIRA\SimHub\MAIRA Refactored - Grip-o-Meter.simhubdash"

[UninstallDelete]
Type: files; Name: "{userstartup}\MAIRA.lnk"

[Code]
var
  GSimHubRoot: string;
  GSimHubExe:  string;
  GRunningSimHubExe: string;   // exe path captured from the live process (most reliable)
  GSimHubWasRunning: Boolean;  // restart SimHub after install/uninstall if we closed it

function DirExistsAndHasSimHubExe(const Dir: string): Boolean;
begin
  Result := FileExists(AddBackslash(Dir) + 'SimHubWPF.exe');
end;

// ---------------------------------------------------------------------------
// SimHub process detection and shutdown.
// Setup replaces plugin DLLs inside the SimHub folder, so SimHub must not be
// running while files are copied. SimHub hides to the tray and ignores
// graceful close requests, so Inno's CloseApplications/Restart Manager
// cannot be relied on for it.
// ---------------------------------------------------------------------------

// Returns True if SimHubWPF.exe is running; ExePath gets its full path when
// WMI can provide it (empty otherwise).
function DetectRunningSimHub(var ExePath: string): Boolean;
var
  WbemLocator, WbemServices, ProcList, Proc: Variant;
  ResultCode: Integer;
begin
  Result := False;
  ExePath := '';

  // Primary: WMI — also yields the exact executable path
  try
    WbemLocator := CreateOleObject('WbemScripting.SWbemLocator');
    WbemServices := WbemLocator.ConnectServer('.', 'root\CIMV2');
    ProcList := WbemServices.ExecQuery('SELECT ExecutablePath FROM Win32_Process WHERE Name = ''SimHubWPF.exe''');
    if ProcList.Count > 0 then
    begin
      Result := True;
      try
        Proc := ProcList.ItemIndex(0);
        ExePath := Proc.ExecutablePath;
      except
        ExePath := '';  // ExecutablePath can be null (e.g. access denied)
      end;
    end;
    Exit;
  except
    Log('WMI process query failed; falling back to tasklist.');
  end;

  // Fallback: tasklist + find (exit code 0 = process found)
  if Exec(ExpandConstant('{cmd}'),
          '/C tasklist /NH /FI "IMAGENAME eq SimHubWPF.exe" | find /I "SimHubWPF.exe" >nul',
          '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    Result := (ResultCode = 0);
end;

// Polls until SimHub is gone or the timeout elapses. True = it exited.
function WaitForSimHubToExit(TimeoutMs: Integer): Boolean;
var
  Elapsed: Integer;
  Dummy: string;
begin
  Elapsed := 0;
  while DetectRunningSimHub(Dummy) do
  begin
    if Elapsed >= TimeoutMs then
    begin
      Result := False;
      Exit;
    end;
    Sleep(500);
    Elapsed := Elapsed + 500;
  end;
  Result := True;
end;

procedure TaskKillSimHub(Force: Boolean);
var
  Params: string;
  ResultCode: Integer;
begin
  if Force then
    Params := '/F /T /IM SimHubWPF.exe'
  else
    Params := '/IM SimHubWPF.exe';
  Exec(ExpandConstant('{sys}\taskkill.exe'), Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Log(Format('taskkill %s -> exit code %d', [Params, ResultCode]));
end;

// Closes SimHub: graceful first, then force, then ask the user to intervene.
// Returns False only if the user cancels.
function EnsureSimHubClosed: Boolean;
begin
  Result := True;

  repeat
    Log('Asking SimHub to close gracefully...');
    TaskKillSimHub(False);
    if WaitForSimHubToExit(5000) then Break;

    Log('Graceful close failed; force-terminating SimHub...');
    TaskKillSimHub(True);
    if WaitForSimHubToExit(5000) then Break;

    // Still running — e.g. SimHub is elevated and we are not. Let the user close it.
    if MsgBox('SimHub must be closed so its plugins can be updated, but it could not be closed automatically.'#13#10#13#10
              + 'Please close SimHub manually (check the system tray), then click Retry.',
              mbError, MB_RETRYCANCEL) = IDCANCEL then
    begin
      Result := False;
      Exit;
    end;
  until False;

  Log('SimHub is closed.');
end;

procedure RestartSimHubIfItWasRunning;
var
  ExeToStart: string;
  ResultCode: Integer;
begin
  if not GSimHubWasRunning then
    Exit;

  ExeToStart := GRunningSimHubExe;
  if (ExeToStart = '') or not FileExists(ExeToStart) then
    ExeToStart := GSimHubExe;

  if (ExeToStart <> '') and FileExists(ExeToStart) then
  begin
    Log('Restarting SimHub: ' + ExeToStart);
    ExecAsOriginalUser(ExeToStart, '', ExtractFileDir(ExeToStart), SW_SHOWNORMAL, ewNoWait, ResultCode);
  end
  else
    Log('SimHub was running but its exe could not be resolved; not restarting it.');
end;

// The documents folder was renamed from "MarvinsAIRA Refactored" to "MAIRA" when the "Refactored"
// naming was retired. Rename the old folder (settings, recordings, calibration, everything) before any
// files are installed, so the [Dirs]/[Files] entries land in the migrated folder instead of creating a
// fresh one beside it. If the rename fails (folder locked etc.) the app performs its own merge
// migration on next startup, so this is best-effort.
procedure MigrateLegacyDocumentsFolder;
var
  OldDir, NewDir: string;
begin
  OldDir := ExpandConstant('{userdocs}\MarvinsAIRA Refactored');
  NewDir := ExpandConstant('{userdocs}\MAIRA');

  if DirExists(OldDir) and not DirExists(NewDir) then
  begin
    if RenameFile(OldDir, NewDir) then
      Log('Migrated documents folder: ' + OldDir + ' -> ' + NewDir)
    else
      Log('Could not rename ' + OldDir + ' to ' + NewDir + '; the app will migrate it on next startup.');
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';

  MigrateLegacyDocumentsFolder;

  GSimHubWasRunning := DetectRunningSimHub(GRunningSimHubExe);
  if not GSimHubWasRunning then
  begin
    Log('SimHub is not running.');
    Exit;
  end;

  if GRunningSimHubExe <> '' then
    Log('SimHub is running from: ' + GRunningSimHubExe)
  else
    Log('SimHub is running (path unknown).');

  if not EnsureSimHubClosed then
    Result := 'Setup cannot continue while SimHub is running.';
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    RestartSimHubIfItWasRunning;
end;

// The uninstaller deletes the plugin DLLs from the SimHub folder, so SimHub
// must be closed then too.
function InitializeUninstall(): Boolean;
begin
  Result := True;

  GSimHubWasRunning := DetectRunningSimHub(GRunningSimHubExe);
  if GSimHubWasRunning then
    Result := EnsureSimHubClosed;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    RestartSimHubIfItWasRunning;
end;

function TryCheckKeyForPath(RootKey: Integer; const SubKey: string; var OutDir: string): Boolean;
var
  DispName, InstallLoc: string;
begin
  Result := False;

  if RegQueryStringValue(RootKey, SubKey, 'DisplayName', DispName) then
  begin
    Log(Format('Found uninstall entry "%s" DisplayName="%s"', [SubKey, DispName]));

    // Be tolerant of minor name changes: just look for "SimHub" anywhere
    if Pos(UpperCase('SimHub'), UpperCase(DispName)) > 0 then
    begin
      // First try InstallLocation
      if RegQueryStringValue(RootKey, SubKey, 'InstallLocation', InstallLoc) then
      begin
        Log('InstallLocation=' + InstallLoc);
        if DirExistsAndHasSimHubExe(InstallLoc) then
        begin
          OutDir := InstallLoc;
          Result := True;
          Exit;
        end;
      end;

      // Then try Inno Setup specific value
      if RegQueryStringValue(RootKey, SubKey, 'Inno Setup: App Path', InstallLoc) then
      begin
        Log('Inno Setup: App Path=' + InstallLoc);
        if DirExistsAndHasSimHubExe(InstallLoc) then
        begin
          OutDir := InstallLoc;
          Result := True;
          Exit;
        end;
      end;
    end;
  end
  else
    Log('No DisplayName for ' + SubKey);
end;

function TryFindSimHubDirFromUninstall(var Dir: string): Boolean;
var
  RootKeys: array[0..2] of Integer;
  BaseKeys: array[0..2] of String;
  I, J: Integer;
  SubKey: string;
  SubKeys: TArrayOfString;
begin
  Result := False;

  // SimHub is a 32-bit per-machine Inno install, so it normally registers under
  // the HKLM WOW6432Node view; the other views cover unusual setups. (HKCU has
  // no WOW6432Node view — per-user installs write straight to Software.)
  RootKeys[0] := HKEY_LOCAL_MACHINE;
  BaseKeys[0] := 'Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall';
  RootKeys[1] := HKEY_LOCAL_MACHINE;
  BaseKeys[1] := 'Software\Microsoft\Windows\CurrentVersion\Uninstall';
  RootKeys[2] := HKEY_CURRENT_USER;
  BaseKeys[2] := 'Software\Microsoft\Windows\CurrentVersion\Uninstall';

  // Fast path: SimHub's typical Inno key name
  for I := 0 to High(RootKeys) do
  begin
    SubKey := BaseKeys[I] + '\SimHub_is1';
    Log('Checking direct key: ' + SubKey);
    if TryCheckKeyForPath(RootKeys[I], SubKey, Dir) then
    begin
      Result := True;
      Exit;
    end;
  end;

  // Fallback: enumerate all uninstall subkeys looking for DisplayName containing "SimHub"
  for I := 0 to High(RootKeys) do
  begin
    Log('Enumerating uninstall key: ' + BaseKeys[I]);

    if RegGetSubkeyNames(RootKeys[I], BaseKeys[I], SubKeys) then
    begin
      for J := 0 to GetArrayLength(SubKeys) - 1 do
      begin
        SubKey := BaseKeys[I] + '\' + SubKeys[J];
        if TryCheckKeyForPath(RootKeys[I], SubKey, Dir) then
        begin
          Result := True;
          Exit;
        end;
      end;
    end
    else
      Log('No subkeys under ' + BaseKeys[I] + ' or access denied');
  end;
end;

function TryFindSimHubInCommonLocations(var Dir: string): Boolean;
var
  Candidates: array[0..1] of String;
  K: Integer;
begin
  Candidates[0] := ExpandConstant('{pf32}\SimHub');
  Candidates[1] := ExpandConstant('{pf}\SimHub');

  for K := 0 to High(Candidates) do
  begin
    Log('Checking common path: ' + Candidates[K]);
    if DirExistsAndHasSimHubExe(Candidates[K]) then
    begin
      Dir := Candidates[K];
      Result := True;
      Exit;
    end;
  end;

  Result := False;
end;

function SimHubRoot(Param: string): string;
begin
  // Cache once
  if GSimHubRoot = '' then
  begin
    Log('Starting SimHub detection...');
    if (GRunningSimHubExe <> '') and DirExistsAndHasSimHubExe(ExtractFileDir(GRunningSimHubExe)) then
    begin
      GSimHubRoot := ExtractFileDir(GRunningSimHubExe);
      Log('SimHub found via its running process at: ' + GSimHubRoot);
    end
    else if TryFindSimHubDirFromUninstall(GSimHubRoot) then
      Log('SimHub found via uninstall registry at: ' + GSimHubRoot)
    else if TryFindSimHubInCommonLocations(GSimHubRoot) then
      Log('SimHub found via common locations at: ' + GSimHubRoot)
    else
      Log('SimHub NOT found; using fallback folder.');

    // Every detection path above verified SimHubWPF.exe exists in the folder
    if GSimHubRoot <> '' then
    begin
      GSimHubExe := AddBackslash(GSimHubRoot) + 'SimHubWPF.exe';
      Log('SimHub exe resolved to: ' + GSimHubExe);
    end
    else
    begin
      // Silent fallback (no UI) — still place the DLL somewhere predictable
      GSimHubRoot := ExpandConstant('{userdocs}\MAIRA\SimHub Plugin');
      ForceDirectories(GSimHubRoot);
      GSimHubExe := '';
      Log('Fallback plugin folder: ' + GSimHubRoot);
    end;
  end;

  Result := GSimHubRoot;
end;
